#!/bin/bash
# COLOR VALIDATION
RED='\033[0;31m'
NC='\033[0m'
gray='\e[1;30m'
Blue='\033[36m'
GREEN='\033[0;32m'
grenbo='\e[92;1m'
yellow='\033[0;33m'
tokgit=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
TIMES="10"
KEY="6071809974:AAENfe_1BAHno9y9-VE91me-0ien_ssPAQ"
COMMAND=$(curl -sS https://raw.githubusercontent.com/xlosx/Tunneling/main/Sandi/cominstall)
URL="https://api.telegram.org/bot$KEY/sendMessage"
MYIP=$(curl -s ipv4.icanhazip.com)
ADMM=$(echo Admin)
ipreg="1"
IZIN=$(curl -sS https://raw.githubusercontent.com/xlosx/Registrasi/main/ipvip | grep $MYIP | awk '{print $5}')
if [ $IZIN = $ADMM ]; then
    echo -e " "
else
    echo -e "\e[31mPermission Denied!\e[0m";
    exit 0
fi

function TeleNotif() {
    TEXT="
---------------
Tambah Lisensi Admin
---------------
Admin Name: <code>${userxx}</code>
Status    : <code>${statusxx}</code>
Chat Id   : <code>${idchat}</code>
---------------
Informasi Lisensi
---------------
1 Bulan: <code>${satubu} Lisensi</code>
2 Bulan: <code>${duabu} Lisensi</code>
3 Bulan: <code>${tigabu} Lisensi</code>
1 Tahun: <code>${satuta}Lisensi</code>
---------------
Registered By : <code>${NamaOwner}</code>
---------------
<b>Thanks To @Mass_Alfin</b>
---------------"
    curl -s --max-time $TIMES -d "chat_id=${idchatx}&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function DoneBos() {
    TeleNotif
    clear
    echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}            ${GREEN}INFORMASI REGISTRASI LISENSI [DONE]${NC}          ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                 ${GREEN}IDENTITAS LISENSI ADMIN${NC}                 ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}     ${Blue}Admin Name ${NC}: ${grenbo}${userxx}${NC}
 ${yellow}│${NC}     ${Blue}Status     ${NC}: ${grenbo}${statusxx}${NC}
 ${yellow}│${NC}     ${Blue}Id Telegram${NC}: ${grenbo}${idchat}${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}             ${GREEN}IDENTITAS ADMIN LISENSI [UPDATE]${NC}            ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}     ${Blue}1 Bulan${NC}: ${grenbo}${satubu} Lisensi${NC}        ${Blue}3 Bulan${NC}: ${grenbo}${tigabu} Lisensi${NC}
 ${yellow}│${NC}     ${Blue}2 Bulan${NC}: ${grenbo}${duabu} Lisensi${NC}        ${Blue}1 Tahun${NC}: ${grenbo}${satuta} Lisensi${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}Notifikasi Lisensi Akan Dikirimkan Oleh Bot Ke Akun [ADMIN]${NC}
      ${yellow}Silahkan Periksa Chat Telegram Dari @alf_robot${NC}"
    read -n 1 -s -r -p "  Press any key to back on menu"
    menu
}

function CekData() {
    if [[ $nstatues = $xstatues ]]; then
        echo " "
    else
        clear
        echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                   ${GREEN}INFORMASI DATA ADMIN${NC}                  ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                ${RED}Menu Ini Hanya Untuk Owner${NC}               ${yellow}│${NC}
 ${yellow}│${NC}              ${grenbo}SALAM HANGAT ALFVPN COMMUNITY${NC}              ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}                    ${yellow}KONTAK REGISTRASI${NC}                    ${yellow}│${NC}
 ${yellow}│${NC}     ${Blue}|Telegram: @Mass_Alfin | WhatsApp: 087749311100|${NC}    ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
        echo -e " "
        exit 0
    fi
}

function VerifData() {
    idchatx=$(curl -sS https://raw.githubusercontent.com/xlosx/Registrasi/main/dataadmin | grep $PassAdminOK | awk '{print $9}')
    NamaOwner=$(curl -sS https://raw.githubusercontent.com/xlosx/Registrasi/main/dataadmin | grep $PassAdminOK | awk '{print $2}')
    nstatues=$(curl -sS https://raw.githubusercontent.com/xlosx/Registrasi/main/dataadmin | grep $PassAdminOK | awk '{print $4}')
    xstatues=$(echo Owner)
    CekData
}

function LOGO() {
    echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                ${GREEN}MEMU TAMBAH LISESNSI ADMIN${NC}               ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
}
 
function CekAdmin() {
    LOGO
    read -p " Password Owner: " PassAdmin
    echo -e " "
    echo -e " [INFO] Password Sedang Kami Periksa Mohon Menunggu"
    sleep 3
    PassAdminOK=$(echo "$PassAdmin" | base64)
    izininstall=$(curl -sS https://raw.githubusercontent.com/xlosx/Registrasi/main/dataadmin | grep $PassAdminOK | awk '{print $3}')
    if [[ $PassAdminOK = $izininstall ]]; then
        VerifData
    else
        clear
        echo -e " ${yellow}┌─────────────────────────────────────────────────────────┐${NC}"
        echo -e " ${yellow}│${NC}                  ${GREEN}INFORMASI DATA ADMIN${NC}                   ${yellow}│${NC}"
        echo -e " ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
        echo -e " ${yellow}┌─────────────────────────────────────────────────────────┐${NC}"
        echo -e " ${yellow}│${NC}     ${RED}Password yang anda masukkan tidak kami ditemukan${NC}    ${yellow}│${NC}"
        echo -e " ${yellow}│${NC}  ${RED}Saat ini anda belum bisa melakukan registrasi lisensi${NC}  ${yellow}│${NC}"
        echo -e " ${yellow}│${NC}    ${RED}silahkan lakukan registrasi Admin terlebih dahulu${NC}    ${yellow}│${NC}"
        echo -e " ${yellow}│${NC}              ${grenbo}SALAM HANGAT ALFVPN COMMUNITY${NC}              ${yellow}│${NC}"
        echo -e " ${yellow}│─────────────────────────────────────────────────────────│${NC}"
        echo -e " ${yellow}│${NC}                    ${yellow}KONTAK REGISTRASI${NC}                    ${yellow}│${NC}"
        echo -e " ${yellow}│${NC}     ${Blue}|Telegram: @Mass_Alfin | WhatsApp: 087749311100|${NC}    ${yellow}│${NC}"
        echo -e " ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
        echo -e " "
        exit 0
    fi
}
rm -rf /root/Registrasi >/dev/null 2>&1
clear
CekAdmin
git clone https://github.com/xlosx/Registrasi.git &> /dev/null
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/root/Registrasi/dataadmin")
clear
LOGO
echo -e "     ${Blue}NO${NC}      ${Blue}User${NC}      ${Blue}Status${NC}  "
echo -e " ${yellow}───────────────────────────────────────────────────────────${NC}"
grep -E "^### " "/root/Registrasi/dataadmin" | cut -d ' ' -f 2,4 | column -t | sort | uniq | nl -s ') '
rm -rf /root/Registrasi >/dev/null 2>&1
echo -e ""
echo -e "  • [NOTE] Tekan CTRL+C to Cancel"
echo -e " ${yellow}───────────────────────────────────────────────────────────${NC}"
until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
    if [[ ${CLIENT_NUMBER} == '1' ]]; then
        read -rp "Select one client [1]: " CLIENT_NUMBER
    else
        read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
    fi
done
read -p "  • Lisensi 1 bulan: " satubz
if [[ -z ${satubz} ]]; then
    satubz="0"
fi
satub=$(echo "${satubz}" | sed 's/[^0-9]*//g')
read -p "  • Lisensi 2 bulan: " duabz
if [[ -z ${duabz} ]]; then
    duabz="0"
fi
duab=$(echo "${duabz}" | sed 's/[^0-9]*//g')
read -p "  • Lisensi 3 bulan: " tigabz
if [[ -z ${tigabz} ]]; then
    tigabz="0"
fi
tigab=$(echo "${tigabz}" | sed 's/[^0-9]*//g')
read -p "  • Lisensi 1 Tahun: " satutz
if [[ -z ${satutz} ]]; then
    satutz="0"
fi
satut=$(echo "${satutz}" | sed 's/[^0-9]*//g')
git clone https://github.com/xlosx/Registrasi.git &> /dev/null
userxx=$(grep -E "^### " "/root/Registrasi/dataadmin" | cut -d ' ' -f 2 | sort | uniq | sed -n "${CLIENT_NUMBER}"p)
sandiii=$(cat /root/Registrasi/dataadmin | grep $userxx | awk '{print $3}')
statusxx=$(cat /root/Registrasi/dataadmin | grep $userxx | awk '{print $4}')
satux=$(cat /root/Registrasi/dataadmin | grep $userxx | awk '{print $5}')
duax=$(cat /root/Registrasi/dataadmin | grep $userxx | awk '{print $6}')
tigax=$(cat /root/Registrasi/dataadmin | grep $userxx | awk '{print $7}')
satuxp=$(cat /root/Registrasi/dataadmin | grep $userxx | awk '{print $8}')
idchat=$(cat /root/Registrasi/dataadmin | grep $userxx | awk '{print $9}')
satubu=$((${satux} + ${satub}))
duabu=$((${duax} + ${duab}))
tigabu=$((${tigax} + ${tigab}))
satuta=$((${satuxp} + ${satut}))
git config --global user.email "daenkona@gmail.com" &> /dev/null
git config --global user.name "xlosx" &> /dev/null
cd /root/Registrasi/
rm -rf .git
git init  &> /dev/null
sed -i "s/### $userxx $sandiii $statusxx $satux $duax $tigax $satuxp $idchat/### $userxx $sandiii $statusxx $satubu $duabu $tigabu $satuta $idchat/g" /root/Registrasi/dataadmin
git add .  &> /dev/null
git commit -m renew &> /dev/null
git branch -M main &> /dev/null
git remote add origin https://github.com/xlosx/Registrasi &> /dev/null
git push -f https://${tokgit}@github.com/xlosx/Registrasi.git &> /dev/null
rm -rf /root/Registrasi
DoneBos