#!/bin/bash
# COLOR VALIDATION
RED='\033[0;31m'
NC='\033[0m'
gray='\e[1;30m'
Blue='\033[36m'
GREEN='\033[0;32m'
grenbo='\e[92;1m'
yellow='\033[0;33m'
tokgit=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
TIMES="10"
KEY="6486088494:AAHK00b5qJoWHCxJtCaOeYUMXhYNOLThu78"
COMMAND=$(curl -sS https://raw.githubusercontent.com/takbebeh/Tunneling/main/Sandi/cominstall)
URL="https://api.telegram.org/bot$KEY/sendMessage"
MYIP=$(curl -s ipv4.icanhazip.com)
ADMM=$(echo Admin)
MOD="Client"
IZIN=$(curl -sS https://raw.githubusercontent.com/takbebeh/Registrasi/main/ipvip | grep $MYIP | awk '{print $5}')
if [ $IZIN = $ADMM ]; then
    echo -e " "
else
    echo -e "\e[31mPermission Denied!\e[0m";
    exit 0
fi

function RegA() {
    git clone https://github.com/takbebeh/Registrasi.git &> /dev/null
    git config --global user.email "alfinproject22@gmail.com" &> /dev/null
    git config --global user.name "takbebeh" &> /dev/null
    cd /root/Registrasi/
    rm -rf .git
    git init  &> /dev/null
    sed -i "s/### $namaadmin $PassAdminOK $statusadmin $satubulan $duabulan $tigabulan $satutahun $idchat/### $namaadmin $PassAdminOK $statusadmin $sisalisensi $duabulan $tigabulan $satutahun $idchat/g" /root/Registrasi/dataadmin
    echo "### $PassAdminMantap $ipreg $clientreg $masalisaktif $namaadmin $MOD" >> /root/Registrasi/client
    git add .  &> /dev/null
    git commit -m renew &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/takbebeh/Registrasi &> /dev/null
    git push -f https://${tokgit}@github.com/takbebeh/Registrasi.git &> /dev/null
    rm -rf /root/Registrasi
    TEXT="
---------------
Registrasi Lisensi Done
---------------
<code>Client Name:</code> <code>${clientreg}</code>
<code>Password   :</code> <code>${passwordreg}</code>
<code>Masa Aktif :</code> <code>${masalisaktif} Hari</code>
---------------
<code>Order By :</code> <code>${namaadmin}</code>
---------------
OS Support
☞ Debian 10 (recommended)
☞ Debian 11
☞ Ubuntu 20.04 LTS
---------------
Command Instalasi:
<code>$COMMAND</code>
---------------
<b>Thanks To @Mass_Alfin</b>
---------------"
    curl -s --max-time $TIMES -d "chat_id=${idchat}&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    clear
    echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}            ${GREEN}INFORMASI REGISTRASI LISENSI [DONE]${NC}          ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                 ${GREEN}IDENTITAS LISENSI CLIENT${NC}                ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}     ${Blue}Client Name${NC}: ${grenbo}${clientreg}${NC}
 ${yellow}│${NC}     ${Blue}Password   ${NC}: ${grenbo}${passwordreg}${NC}
 ${yellow}│${NC}     ${Blue}Masa Aktif ${NC}: ${grenbo}${masalisaktif} Hari${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}             ${GREEN}IDENTITAS ADMIN LISENSI [UPDATE]${NC}            ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}  ${Blue}Admin Name${NC}: ${grenbo}${namaadmin}${NC}   ${Blue}Status Admin${NC}: ${yellow}${statusadmin}${NC}
 ${yellow}│${NC}     ${Blue}1 Bulan${NC}: ${grenbo}${sisalisensi} Lisensi${NC}        ${Blue}3 Bulan${NC}: ${grenbo}${tigabulan} Lisensi${NC}
 ${yellow}│${NC}     ${Blue}2 Bulan${NC}: ${grenbo}${duabulan} Lisensi${NC}        ${Blue}1 Tahun${NC}: ${grenbo}${satutahun} Lisensi${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}Notifikasi Lisensi Akan Dikirimkan Oleh Bot Ke Akun [ADMIN]${NC}
      ${yellow}Silahkan Periksa Chat Telegram Dari @alf_robot${NC}"
    read -n 1 -s -r -p "  Press any key to back on menu"
    menu
}

function RegB() {
    git clone https://github.com/takbebeh/Registrasi.git &> /dev/null
    git config --global user.email "alfinproject22@gmail.com" &> /dev/null
    git config --global user.name "takbebeh" &> /dev/null
    cd /root/Registrasi/
    rm -rf .git
    git init  &> /dev/null
    sed -i "s/### $namaadmin $PassAdminOK $statusadmin $satubulan $duabulan $tigabulan $satutahun $idchat/### $namaadmin $PassAdminOK $statusadmin $satubulan $sisalisensi $tigabulan $satutahun $idchat/g" /root/Registrasi/dataadmin
    echo "### $PassAdminMantap $ipreg $clientreg $masalisaktif $namaadmin $MOD" >> /root/Registrasi/client
    git add .  &> /dev/null
    git commit -m renew &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/takbebeh/Registrasi &> /dev/null
    git push -f https://${tokgit}@github.com/takbebeh/Registrasi.git &> /dev/null
    rm -rf /root/Registrasi
    TEXT="
---------------
Registrasi Lisensi Done
---------------
<code>Client Name:</code> <code>${clientreg}</code>
<code>Password   :</code> <code>${passwordreg}</code>
<code>Masa Aktif :</code> <code>${masalisaktif} Hari</code>
---------------
<code>Order By :</code> <code>${namaadmin}</code>
---------------
OS Support
☞ Debian 10 (recommended)
☞ Debian 11
☞ Ubuntu 20.04 LTS
---------------
Command Instalasi:
<code>$COMMAND</code>
---------------
<b>Thanks To @Mass_Alfin</b>
---------------"
    curl -s --max-time $TIMES -d "chat_id=${idchat}&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    clear
    echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}            ${GREEN}INFORMASI REGISTRASI LISENSI [DONE]${NC}          ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                 ${GREEN}IDENTITAS LISENSI CLIENT${NC}                ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}     ${Blue}Client Name${NC}: ${grenbo}${clientreg}${NC}
 ${yellow}│${NC}     ${Blue}Password   ${NC}: ${grenbo}${passwordreg}${NC}
 ${yellow}│${NC}     ${Blue}Masa Aktif ${NC}: ${grenbo}${masalisaktif} Hari${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}             ${GREEN}IDENTITAS ADMIN LISENSI [UPDATE]${NC}            ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}  ${Blue}Admin Name${NC}: ${grenbo}${namaadmin}${NC}   ${Blue}Status Admin${NC}: ${yellow}${statusadmin}${NC}
 ${yellow}│${NC}     ${Blue}1 Bulan${NC}: ${grenbo}${satubulan} Lisensi${NC}        ${Blue}3 Bulan${NC}: ${grenbo}${tigabulan} Lisensi${NC}
 ${yellow}│${NC}     ${Blue}2 Bulan${NC}: ${grenbo}${sisalisensi} Lisensi${NC}        ${Blue}1 Tahun${NC}: ${grenbo}${satutahun} Lisensi${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}Notifikasi Lisensi Akan Dikirimkan Oleh Bot Ke Akun [ADMIN]${NC}
      ${yellow}Silahkan Periksa Chat Telegram Dari @alf_robot${NC}"
    read -n 1 -s -r -p "  Press any key to back on menu"
    menu
}

function RegC() {
    git clone https://github.com/takbebeh/Registrasi.git &> /dev/null
    git config --global user.email "alfinproject22@gmail.com" &> /dev/null
    git config --global user.name "takbebeh" &> /dev/null
    cd /root/Registrasi/
    rm -rf .git
    git init  &> /dev/null
    sed -i "s/### $namaadmin $PassAdminOK $statusadmin $satubulan $duabulan $tigabulan $satutahun $idchat/### $namaadmin $PassAdminOK $statusadmin $satubulan $duabulan $sisalisensi $satutahun $idchat/g" /root/Registrasi/dataadmin
    echo "### $PassAdminMantap $ipreg $clientreg $masalisaktif $namaadmin $MOD" >> /root/Registrasi/client
    git add .  &> /dev/null
    git commit -m renew &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/takbebeh/Registrasi &> /dev/null
    git push -f https://${tokgit}@github.com/takbebeh/Registrasi.git &> /dev/null
    rm -rf /root/Registrasi
    TEXT="
---------------
Registrasi Lisensi Done
---------------
<code>Client Name:</code> <code>${clientreg}</code>
<code>Password   :</code> <code>${passwordreg}</code>
<code>Masa Aktif :</code> <code>${masalisaktif} Hari</code>
---------------
<code>Order By :</code> <code>${namaadmin}</code>
---------------
OS Support
☞ Debian 10 (recommended)
☞ Debian 11
☞ Ubuntu 20.04 LTS
---------------
Command Instalasi:
<code>$COMMAND</code>
---------------
<b>Thanks To @Mass_Alfin</b>
---------------"
    curl -s --max-time $TIMES -d "chat_id=${idchat}&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    clear
    echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}            ${GREEN}INFORMASI REGISTRASI LISENSI [DONE]${NC}          ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                 ${GREEN}IDENTITAS LISENSI CLIENT${NC}                ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}     ${Blue}Client Name${NC}: ${grenbo}${clientreg}${NC}
 ${yellow}│${NC}     ${Blue}Password   ${NC}: ${grenbo}${passwordreg}${NC}
 ${yellow}│${NC}     ${Blue}Masa Aktif ${NC}: ${grenbo}${masalisaktif} Hari${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}             ${GREEN}IDENTITAS ADMIN LISENSI [UPDATE]${NC}            ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}  ${Blue}Admin Name${NC}: ${grenbo}${namaadmin}${NC}   ${Blue}Status Admin${NC}: ${yellow}${statusadmin}${NC}
 ${yellow}│${NC}     ${Blue}1 Bulan${NC}: ${grenbo}${satubulan} Lisensi${NC}        ${Blue}3 Bulan${NC}: ${grenbo}${sisalisensi} Lisensi${NC}
 ${yellow}│${NC}     ${Blue}2 Bulan${NC}: ${grenbo}${duabulan} Lisensi${NC}        ${Blue}1 Tahun${NC}: ${grenbo}${satutahun} Lisensi${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}Notifikasi Lisensi Akan Dikirimkan Oleh Bot Ke Akun [ADMIN]${NC}
      ${yellow}Silahkan Periksa Chat Telegram Dari @alf_robot${NC}"
    read -n 1 -s -r -p "  Press any key to back on menu"
    menu
}

function RegD() {
    git clone https://github.com/takbebeh/Registrasi.git &> /dev/null
    git config --global user.email "alfinproject22@gmail.com" &> /dev/null
    git config --global user.name "takbebeh" &> /dev/null
    cd /root/Registrasi/
    rm -rf .git
    git init  &> /dev/null
    sed -i "s/### $namaadmin $PassAdminOK $statusadmin $satubulan $duabulan $tigabulan $satutahun $idchat/### $namaadmin $PassAdminOK $statusadmin $satubulan $duabulan $tigabulan $sisalisensi $idchat/g" /root/Registrasi/dataadmin
    echo "### $PassAdminMantap $ipreg $clientreg $masalisaktif $namaadmin $MOD" >> /root/Registrasi/client
    git add .  &> /dev/null
    git commit -m renew &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/takbebeh/Registrasi &> /dev/null
    git push -f https://${tokgit}@github.com/takbebeh/Registrasi.git &> /dev/null
    rm -rf /root/Registrasi
    TEXT="
---------------
Registrasi Lisensi Done
---------------
<code>Client Name:</code> <code>${clientreg}</code>
<code>Password   :</code> <code>${passwordreg}</code>
<code>Masa Aktif :</code> <code>${masalisaktif} Hari</code>
---------------
<code>Order By :</code> <code>${namaadmin}</code>
---------------
OS Support
☞ Debian 10 (recommended)
☞ Debian 11
☞ Ubuntu 20.04 LTS
---------------
Command Instalasi:
<code>$COMMAND</code>
---------------
<b>Thanks To @Mass_Alfin</b>
---------------"
    curl -s --max-time $TIMES -d "chat_id=${idchat}&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    clear
    echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}            ${GREEN}INFORMASI REGISTRASI LISENSI [DONE]${NC}          ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                 ${GREEN}IDENTITAS LISENSI CLIENT${NC}                ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}     ${Blue}Client Name${NC}: ${grenbo}${clientreg}${NC}
 ${yellow}│${NC}     ${Blue}Password   ${NC}: ${grenbo}${passwordreg}${NC}
 ${yellow}│${NC}     ${Blue}Masa Aktif ${NC}: ${grenbo}${masalisaktif} Hari${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}             ${GREEN}IDENTITAS ADMIN LISENSI [UPDATE]${NC}            ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}  ${Blue}Admin Name${NC}: ${grenbo}${namaadmin}${NC}   ${Blue}Status Admin${NC}: ${yellow}${statusadmin}${NC}
 ${yellow}│${NC}     ${Blue}1 Bulan${NC}: ${grenbo}${satubulan} Lisensi${NC}        ${Blue}3 Bulan${NC}: ${grenbo}${tigabulan} Lisensi${NC}
 ${yellow}│${NC}     ${Blue}2 Bulan${NC}: ${grenbo}${duabulan} Lisensi${NC}        ${Blue}1 Tahun${NC}: ${grenbo}${sisalisensi} Lisensi${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}Notifikasi Lisensi Akan Dikirimkan Oleh Bot Ke Akun [ADMIN]${NC}
      ${yellow}Silahkan Periksa Chat Telegram Dari @alf_robot${NC}"
    read -n 1 -s -r -p "  Press any key to back on menu"
    menu
}

function CekA() {
    sisalisensi=$(($satubulan - $ipreg))
    if [ $satubulan = 0 ]; then
        clear
        echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                  ${GREEN}INFORMASI DATA ADMIN${NC}                   ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}   ${RED}Lisensi anda tidak cukup untuk melakukan registrasi${NC}   ${yellow}│${NC}
 ${yellow}│${NC}  ${RED}Saat ini anda belum bisa melakukan registrasi lisensi${NC}  ${yellow}│${NC}
 ${yellow}│${NC}   ${RED}silahkan tambah lisensi Admin Kamu terlebih dahulu${NC}    ${yellow}│${NC}
 ${yellow}│${NC}              ${grenbo}SALAM HANGAT ALFVPN COMMUNITY${NC}              ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}                    ${yellow}KONTAK REGISTRASI${NC}                    ${yellow}│${NC}
 ${yellow}│${NC}     ${Blue}|Telegram: @Mass_Alfin | WhatsApp: 087749311100|${NC}    ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
        echo -e " "
        exit 0
    else
        masalisaktif="30"
        RegA
    fi
}

function CekB() {
    sisalisensi=$(($duabulan - $ipreg))
    if [ $duabulan = 0 ]; then
        clear
        echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                  ${GREEN}INFORMASI DATA ADMIN${NC}                   ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}   ${RED}Lisensi anda tidak cukup untuk melakukan registrasi${NC}   ${yellow}│${NC}
 ${yellow}│${NC}  ${RED}Saat ini anda belum bisa melakukan registrasi lisensi${NC}  ${yellow}│${NC}
 ${yellow}│${NC}   ${RED}silahkan tambah lisensi Admin Kamu terlebih dahulu${NC}    ${yellow}│${NC}
 ${yellow}│${NC}              ${grenbo}SALAM HANGAT ALFVPN COMMUNITY${NC}              ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}                    ${yellow}KONTAK REGISTRASI${NC}                    ${yellow}│${NC}
 ${yellow}│${NC}     ${Blue}|Telegram: @Mass_Alfin | WhatsApp: 087749311100|${NC}    ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
        echo -e " "
        exit 0
    else
        masalisaktif="60"
        RegB
    fi
}

function CekC() {
    sisalisensi=$(($tigabulan - $ipreg))
    if [ $tigabulan = 0 ]; then
        clear
        echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                  ${GREEN}INFORMASI DATA ADMIN${NC}                   ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}   ${RED}Lisensi anda tidak cukup untuk melakukan registrasi${NC}   ${yellow}│${NC}
 ${yellow}│${NC}  ${RED}Saat ini anda belum bisa melakukan registrasi lisensi${NC}  ${yellow}│${NC}
 ${yellow}│${NC}   ${RED}silahkan tambah lisensi Admin Kamu terlebih dahulu${NC}    ${yellow}│${NC}
 ${yellow}│${NC}              ${grenbo}SALAM HANGAT ALFVPN COMMUNITY${NC}              ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}                    ${yellow}KONTAK REGISTRASI${NC}                    ${yellow}│${NC}
 ${yellow}│${NC}     ${Blue}|Telegram: @Mass_Alfin | WhatsApp: 087749311100|${NC}    ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
        echo -e " "
        exit 0
    else
        masalisaktif="90"
        RegC
    fi
}

function CekD() {
    sisalisensi=$(($satutahun - ${ipreg}))
    if [ $satutahun = 0 ]; then
        clear
        echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                  ${GREEN}INFORMASI DATA ADMIN${NC}                   ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}   ${RED}Lisensi anda tidak cukup untuk melakukan registrasi${NC}   ${yellow}│${NC}
 ${yellow}│${NC}  ${RED}Saat ini anda belum bisa melakukan registrasi lisensi${NC}  ${yellow}│${NC}
 ${yellow}│${NC}   ${RED}silahkan tambah lisensi Admin Kamu terlebih dahulu${NC}    ${yellow}│${NC}
 ${yellow}│${NC}              ${grenbo}SALAM HANGAT ALFVPN COMMUNITY${NC}              ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}                    ${yellow}KONTAK REGISTRASI${NC}                    ${yellow}│${NC}
 ${yellow}│${NC}     ${Blue}|Telegram: @Mass_Alfin | WhatsApp: 087749311100|${NC}    ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
        echo -e " "
        exit 0
    else
        masalisaktif="360"
        RegD
    fi
}

function PilihMasaAktif() {
    clear
    echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}               ${GREEN}INFORMASI REGISTRASI LISENSI${NC}              ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                 ${GREEN}IDENTITAS LISENSI CLIENT${NC}                ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}     ${Blue}Client Name${NC}: ${grenbo}${clientreg}${NC}
 ${yellow}│${NC}     ${Blue}Password   ${NC}: ${grenbo}${passwordreg}${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                 ${GREEN}IDENTITAS ADMIN LISENSI${NC}                 ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}  ${Blue}Admin Name${NC}: ${grenbo}${namaadmin}${NC}   ${Blue}Status Admin${NC}: ${yellow}${statusadmin}${NC}
 ${yellow}│${NC}     ${Blue}1 Bulan${NC}: ${grenbo}${satubulan} Lisensi${NC}        ${Blue}3 Bulan${NC}: ${grenbo}${tigabulan} Lisensi${NC}
 ${yellow}│${NC}     ${Blue}2 Bulan${NC}: ${grenbo}${duabulan} Lisensi${NC}        ${Blue}1 Tahun${NC}: ${grenbo}${satutahun} Lisensi${NC}
 ${yellow}│${NC}
 ${yellow}│${NC} ${RED}NB${NC}: ${yellow}A. Pastikan Client Name Sudah Benar${NC}
 ${yellow}│${NC}     ${yellow}B. Pastikan lisesnsi ada tersedia sesuai kebutuhan${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                ${GREEN}PILIH MASA AKTIF LISENSI${NC}                 ${yellow}│${NC}
 ${yellow}│${NC}      [${yellow}1${NC}] ${Blue}Aktif 30 Hari${NC}          [${yellow}3${NC}] ${Blue}Aktif 90 Hari${NC}       ${yellow}│${NC}
 ${yellow}│${NC}      [${yellow}2${NC}] ${Blue}Aktif 60 Hari${NC}          [${yellow}4${NC}] ${Blue}Aktif 360 Hari${NC}      ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
    [${yellow}INFO${NC}] ${RED}Tekan CTRL + C Untuk Cancel${NC}"
    read -p "Masukkan Pilihan [1-4] : " amasaaktif
    case $amasaaktif in
        1) CekA ;;
        2) CekB ;;
        3) CekC ;;
        4) CekD ;;
        *) exit 0 ;;
    esac
}

function RegisLisen() {
    clear
    git clone https://github.com/takbebeh/Registrasi.git &> /dev/null
    namaadmin=$(cat /root/Registrasi/dataadmin | grep $PassAdminOK | awk '{print $2}')
    statusadmin=$(cat /root/Registrasi/dataadmin | grep $PassAdminOK | awk '{print $4}')
    satubulan=$(cat /root/Registrasi/dataadmin | grep $PassAdminOK | awk '{print $5}')
    duabulan=$(cat /root/Registrasi/dataadmin | grep $PassAdminOK | awk '{print $6}')
    tigabulan=$(cat /root/Registrasi/dataadmin | grep $PassAdminOK | awk '{print $7}')
    satutahun=$(cat /root/Registrasi/dataadmin | grep $PassAdminOK | awk '{print $8}')
    idchat=6486088494
    rm -rf /root/Registrasi
    clear
    echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                   ${GREEN}REGISTRASI LISENSI${NC}                    ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}                 ${GREEN}IDENTITAS ADMIN LISENSI${NC}                 ${yellow}│${NC}
 ${yellow}│─────────────────────────────────────────────────────────│${NC}
 ${yellow}│${NC}  ${Blue}Admin Name${NC}: ${grenbo}${namaadmin}${NC}   ${Blue}Status Admin${NC}: ${yellow}${statusadmin}${NC}
 ${yellow}│${NC}     ${Blue}1 Bulan${NC}: ${grenbo}${satubulan} Lisensi${NC}        ${Blue}3 Bulan${NC}: ${grenbo}${tigabulan} Lisensi${NC}
 ${yellow}│${NC}     ${Blue}2 Bulan${NC}: ${grenbo}${duabulan} Lisensi${NC}        ${Blue}1 Tahun${NC}: ${grenbo}${satutahun} Lisensi${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
    until [[ $clientreg =~ ^[a-zA-Z0-9_]+$ ]]; do
        echo -e "    ${RED}NB${NC}: ${yellow}A. Client Name Harus Terisi${NC}"
        echo -e "        ${yellow}B. Client Name tidak boleh Memakai Karakter Spasi${NC}"
        read -rp "   Nama Client: " clientreg
    done
    passwordreg=`</dev/urandom tr -dc a-z1-9 | head -c8`
    ipreg="1"
    PassAdminMantap=$(echo "$passwordreg" | base64)
    PilihMasaAktif
}

function LOGO() {
    echo -e "
 ${yellow}┌─────────────────────────────────────────────────────────┐${NC}
 ${yellow}│${NC}             ${GREEN}MENU REGISTRASI LISENSI [ADMIN]${NC}             ${yellow}│${NC}
 ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
}
function CekAdmin() {
    LOGO
    read -p " Password Admin: " PassAdmin
    echo -e " "
    echo -e " [INFO] Password Sedang Kami Periksa Mohon Menunggu"
    sleep 3
    PassAdminOK=$(echo "$PassAdmin" | base64)
    izininstall=$(curl -sS https://raw.githubusercontent.com/takbebeh/Registrasi/main/dataadmin | grep $PassAdminOK | awk '{print $3}')
    if [[ $PassAdminOK = $izininstall ]]; then
        RegisLisen
    else
        clear
        echo -e " ${yellow}┌─────────────────────────────────────────────────────────┐${NC}"
        echo -e " ${yellow}│${NC}                  ${GREEN}INFORMASI DATA ADMIN${NC}                   ${yellow}│${NC}"
        echo -e " ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
        echo -e " ${yellow}┌─────────────────────────────────────────────────────────┐${NC}"
        echo -e " ${yellow}│${NC}     ${RED}Password yang anda masukkan tidak kami ditemukan${NC}    ${yellow}│${NC}"
        echo -e " ${yellow}│${NC}  ${RED}Saat ini anda belum bisa melakukan registrasi lisensi${NC}  ${yellow}│${NC}"
        echo -e " ${yellow}│${NC}    ${RED}silahkan lakukan registrasi Admin terlebih dahulu${NC}    ${yellow}│${NC}"
        echo -e " ${yellow}│${NC}              ${grenbo}SALAM HANGAT ALFVPN COMMUNITY${NC}              ${yellow}│${NC}"
        echo -e " ${yellow}│─────────────────────────────────────────────────────────│${NC}"
        echo -e " ${yellow}│${NC}                    ${yellow}KONTAK REGISTRASI${NC}                    ${yellow}│${NC}"
        echo -e " ${yellow}│${NC}     ${Blue}|Telegram: @Mass_Alfin | WhatsApp: 087749311100|${NC}    ${yellow}│${NC}"
        echo -e " ${yellow}└─────────────────────────────────────────────────────────┘${NC}"
        echo -e " "
        exit 0
    fi
}
clear
CekAdmin